web:
    image: nginx:latest
    ports:
        - "5081:80"
    volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:
    build: ./
    volumes:
        - ./code:/code
    links:
        - db
db:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_USER: dev
        MYSQL_PASSWORD: 123456
        MYSQL_DATABASE: myapp
    volumes:
        - ./database:/var/lib/mysql

